import { Navbar } from "@/components/navbar"
import { Providers } from "./providers"

import "../styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning className="snap-y snap-mandatory scroll-smooth">
      <body>
        <Providers themeProps={{ enableSystem: true, children }}>
          <div className="relative flex flex-col h-screen">
            <Navbar />
            <main>
              {children}
            </main>
            <footer className="w-full flex items-center justify-center py-3">
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  )
}
